spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      model: llama3.2
    chat:
      options:
        model: llama3.2
        temperature: 0.7
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework: DEBUG
    com.personaltraining: DEBUG
    org.springframework.ai: TRACE